CREATE TABLE `USER` (
  USER_ID varchar(45) NOT NULL PRIMARY KEY,
  USER_NAME varchar(45) NOT NULL,
  USER_PW varchar(255) NOT NULL,
  EMAIL varchar(45)
);

CREATE TABLE `BOARD` (
  BOARD_ID int NOT NULL AUTO_INCREMENT,
  USER_ID varchar(45) NOT NULL,
  POST_TITLE varchar(255) NOT NULL,
  IMAGE_PATH varchar(255),
  URL varchar(2083),
  POST_CONTENTS text NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  REPORT_COUNT int NOT NULL,
  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_ID),
  CONSTRAINT FK_BOARD FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID) ON DELETE CASCADE
);

CREATE TABLE `COMMENT` (
  COMMENT_ID int NOT NULL AUTO_INCREMENT,
  BOARD_ID int NOT NULL,
  USER_ID varchar(45) NOT NULL,
  COMMENT_CONTENTS text NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  REPORT_COUNT int NOT NULL,
  CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENT_ID),
  CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE
);

CREATE TABLE `ANALYSIS` (
  ANALYSIS_ID int NOT NULL AUTO_INCREMENT,
  USER_ID varchar(45) NOT NULL,
  ANALYSIS_TITLE varchar(255) NOT NULL,
  IP_ADDRESS varchar(45) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ANALYSIS_DETAILS_JSON text,
  ANALYZED_URL varchar(2083),
  IP_LOCATION varchar(255),
  REASON text,
  RISK_LEVEL enum('DANGEROUS', 'SAFE', 'SUSPICIOUS'),
  SAFE_BROWSING_RESULT varchar(50),
  CONSTRAINT PK_ANALYSIS PRIMARY KEY (ANALYSIS_ID),
  CONSTRAINT FK_ANALYSIS FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID) ON DELETE CASCADE
);