CREATE TABLE `USER` (
  USER_ID varchar(45) PRIMARY KEY NOT NULL,
  USER_NAME varchar(45) NOT NULL,
  USER_PW varchar(255) NOT NULL,
  PHONE VARCHAR(20) NOT NULL
);

CREATE TABLE BOARD (
  BOARD_ID int NOT NULL AUTO_INCREMENT,
  USER_ID varchar(45) NOT NULL,
  POST_TITLE VARCHAR(255) NOT NULL,
  IMAGE_PATH VARCHAR(255),
  URL VARCHAR(2083),
  POST_CONTENTS TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_ID),
  CONSTRAINT FK_BOARD FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID) ON DELETE CASCADE
);

CREATE TABLE `COMMENT` (
  COMMENT_ID int NOT NULL AUTO_INCREMENT,
  BOARD_ID int NOT NULL,
  USER_ID varchar(45) NOT NULL,
  COMMENT_CONTENTS TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENT_ID),
  CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE
);

CREATE TABLE `ANALYSIS`(
  ANALYSIS_ID int NOT NULL AUTO_INCREMENT,
  USER_ID varchar(45) NOT NULL,
  SCAN_RESULT varchar(25) NOT NULL,
  ANALYSIS_URL varchar(2083) NOT NULL,
  ANALYSIS_TITLE varchar(255) NOT NULL,
  IP_ADDRESS varchar(45) NOT NULL,
  created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_ANALYSIS PRIMARY KEY (ANALYSIS_ID),
  CONSTRAINT FK_ANALYSIS FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID) ON DELETE CASCADE
);
